### ISSUE TITLE
Atom feed link broken

### ISSUE THREAD

**Issue by gjost** [pydanny/daniel-blog-fasthtml#5]
I reached your blog via this repo, linked to from the FastHTML post on Hacker News.  The link in the repo description points to danielfeldroycom-production.up.railway.app, which is fine but then your [Atom feed link](https://danielfeldroycom-production.up.railway.app/feeds/atom.xml) is broken.  The link from [daniel.feldroy.com](https://daniel.feldroy.com/feeds/atom.xml) works fine.

**Comment by pydanny** [comment]
Just fixed the feed!
