### ISSUE TITLE
Missing 404 handler logic in router for slugs and markdown pages

### ISSUE THREAD

**Issue by stephenhibbert** [pydanny/daniel-blog-fasthtml#6]
Hey Danny, firstly huge thanks for putting this out there. It's been a joy to read through and adapt for my own blog.

Small bug I spotted, if you go to a route that doesn't exist e.g. https://daniel.feldroy.com/hello you see an error instead of the 404 page.

**Comment by pydanny** [comment]
Whoa! Just saw these issues! Thanks for posting!
